version: '3'

services:
 apache:
  build:
   context: .
   dockerfile: docker/apache/Dockerfile
  volumes:
  #website html-php
   - ./gdaym8:/var/www/html

  #DVD
   - /run/media:/run/media

  #SQLite DB
   - ./mydatabase.sqlite:/var/www/db/mydatabase.sqlite

  ports:
   - "80:80"
   - "443:443"

  environment:
   - SQLITE_DATABASE_PATH=/var/www/db/mydatabase.sqlite

  networks:
   - backend

  restart: always

networks:
 backend:
   driver: bridge

